import { z } from "zod";
export declare const CreateEventSchema: z.ZodObject<{
    title: z.ZodString;
    description: z.ZodString;
    location: z.ZodString;
    startDate: z.ZodString;
    endDate: z.ZodString;
    capacity: z.ZodNumber;
    ticketPrice: z.ZodNumber;
    currency: z.ZodDefault<z.ZodEnum<["USD", "EUR", "GBP"]>>;
    imageUrl: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    title?: string;
    description?: string;
    location?: string;
    startDate?: string;
    endDate?: string;
    capacity?: number;
    ticketPrice?: number;
    currency?: "USD" | "EUR" | "GBP";
    imageUrl?: string;
}, {
    title?: string;
    description?: string;
    location?: string;
    startDate?: string;
    endDate?: string;
    capacity?: number;
    ticketPrice?: number;
    currency?: "USD" | "EUR" | "GBP";
    imageUrl?: string;
}>;
export declare const UpdateEventSchema: z.ZodObject<{
    title: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    location: z.ZodOptional<z.ZodString>;
    startDate: z.ZodOptional<z.ZodString>;
    endDate: z.ZodOptional<z.ZodString>;
    capacity: z.ZodOptional<z.ZodNumber>;
    ticketPrice: z.ZodOptional<z.ZodNumber>;
    currency: z.ZodOptional<z.ZodDefault<z.ZodEnum<["USD", "EUR", "GBP"]>>>;
    imageUrl: z.ZodOptional<z.ZodOptional<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    title?: string;
    description?: string;
    location?: string;
    startDate?: string;
    endDate?: string;
    capacity?: number;
    ticketPrice?: number;
    currency?: "USD" | "EUR" | "GBP";
    imageUrl?: string;
}, {
    title?: string;
    description?: string;
    location?: string;
    startDate?: string;
    endDate?: string;
    capacity?: number;
    ticketPrice?: number;
    currency?: "USD" | "EUR" | "GBP";
    imageUrl?: string;
}>;
export declare const EventSchema: z.ZodObject<{
    title: z.ZodString;
    description: z.ZodString;
    location: z.ZodString;
    startDate: z.ZodString;
    endDate: z.ZodString;
    capacity: z.ZodNumber;
    ticketPrice: z.ZodNumber;
    currency: z.ZodDefault<z.ZodEnum<["USD", "EUR", "GBP"]>>;
    imageUrl: z.ZodOptional<z.ZodString>;
    id: z.ZodString;
    organizerId: z.ZodOptional<z.ZodString>;
    organizerName: z.ZodOptional<z.ZodString>;
    availableSeats: z.ZodNumber;
    createdAt: z.ZodString;
    updatedAt: z.ZodString;
}, "strip", z.ZodTypeAny, {
    title?: string;
    description?: string;
    location?: string;
    startDate?: string;
    endDate?: string;
    capacity?: number;
    ticketPrice?: number;
    currency?: "USD" | "EUR" | "GBP";
    imageUrl?: string;
    id?: string;
    organizerId?: string;
    organizerName?: string;
    availableSeats?: number;
    createdAt?: string;
    updatedAt?: string;
}, {
    title?: string;
    description?: string;
    location?: string;
    startDate?: string;
    endDate?: string;
    capacity?: number;
    ticketPrice?: number;
    currency?: "USD" | "EUR" | "GBP";
    imageUrl?: string;
    id?: string;
    organizerId?: string;
    organizerName?: string;
    availableSeats?: number;
    createdAt?: string;
    updatedAt?: string;
}>;
export type CreateEventDto = z.infer<typeof CreateEventSchema>;
export type UpdateEventDto = z.infer<typeof UpdateEventSchema>;
export type EventDto = z.infer<typeof EventSchema>;
